const jiraSection=document.querySelector('.agent-platform');if(jiraSection)jiraSection.id='jira';
const menu=document.querySelector('.menu'),header=document.querySelector('header');menu.addEventListener('click',()=>{const open=header.classList.toggle('open');menu.textContent=open?'Close':'Menu';menu.setAttribute('aria-expanded',open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,n=+el.dataset.count,start=performance.now();function run(now){let p=Math.min((now-start)/1100,1);el.textContent=Number.isInteger(n)?Math.round(n*p):(n*p).toFixed(1);if(p<1)requestAnimationFrame(run)}requestAnimationFrame(run);io.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>io.observe(el));
document.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,email=f.querySelector('input').value,button=f.querySelector('button'),message=f.querySelector('p');button.disabled=true;button.textContent='Sending…';message.textContent='';try{const response=await fetch('https://formsubmit.co/ajax/info@thecybersol.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email,_replyto:email,_subject:'New demo request — thecybersol',request:'Product demo request',source:location.href})}),data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to send');message.textContent=data.message||'Thanks — your request has been sent to info@thecybersol.com.';if(data.success!=='false'&&data.success!==false)f.reset()}catch(error){message.textContent='We could not send the form. Please email info@thecybersol.com directly.'}finally{button.disabled=false;button.textContent='Request your demo →'}});

const resourceContent=[
  {label:'THREAT RESEARCH',title:'How attackers are operationalizing AI—and how defenders can get ahead',body:'Threat actors are using generative AI to accelerate reconnaissance, produce convincing social engineering, and adapt attacks faster. CyberSol helps defenders respond with unified telemetry, behavioral detection, automated investigation, and human-governed containment.',points:['Recognize AI-enabled attack patterns','Reduce investigation time with correlated evidence','Build safe, governed automation into incident response']},
  {label:'EXECUTIVE GUIDE',title:'The security leader’s blueprint for responsible AI adoption',body:'A practical framework for introducing autonomous capabilities into security operations without losing control. Start with high-volume, evidence-rich workflows, define approval boundaries, and measure quality alongside speed.',points:['Select the right first use cases','Define permissions and human approval points','Measure accuracy, time saved, and risk reduced']},
  {label:'CUSTOMER STORY',title:'How a global manufacturer transformed incident response',body:'A distributed manufacturer unified endpoint, identity, cloud, and network signals to eliminate manual handoffs. Automated enrichment gave analysts a complete incident timeline and enabled containment in 4.2 minutes.',points:['Unified fragmented security data','Automated triage and evidence collection','Reduced mean time to contain to 4.2 minutes']}
];
const modal=document.createElement('div');modal.className='resource-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="resource-dialog" role="dialog" aria-modal="true" aria-labelledby="resource-title"><button class="resource-close" aria-label="Close resource">×</button><p class="resource-label"></p><h2 id="resource-title"></h2><p class="resource-body"></p><ul></ul><a class="btn" href="#demo">Discuss this with our team →</a></div>';document.body.appendChild(modal);
const closeResource=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')};
document.querySelectorAll('.resources article').forEach((card,index)=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',`Open ${resourceContent[index].title}`);const open=()=>{const item=resourceContent[index],dialog=modal.querySelector('.resource-dialog');dialog.querySelector('.resource-label').textContent=item.label;dialog.querySelector('h2').textContent=item.title;dialog.querySelector('.resource-body').textContent=item.body;dialog.querySelector('ul').innerHTML=item.points.map(point=>`<li>${point}</li>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.resource-close').focus()};card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});
modal.querySelector('.resource-close').addEventListener('click',closeResource);modal.addEventListener('click',e=>{if(e.target===modal)closeResource()});modal.querySelector('a').addEventListener('click',closeResource);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeResource()});

// Subtle live network wallpaper. It pauses when the tab is hidden and respects reduced-motion.
const liveCanvas=document.createElement('canvas');liveCanvas.className='live-wallpaper';liveCanvas.setAttribute('aria-hidden','true');document.body.prepend(liveCanvas);const ctx=liveCanvas.getContext('2d'),motionOK=!matchMedia('(prefers-reduced-motion: reduce)').matches;let particles=[],mouse={x:-9999,y:-9999},frame;
function sizeWallpaper(){const ratio=Math.min(devicePixelRatio||1,2);liveCanvas.width=innerWidth*ratio;liveCanvas.height=innerHeight*ratio;liveCanvas.style.width=`${innerWidth}px`;liveCanvas.style.height=`${innerHeight}px`;ctx.setTransform(ratio,0,0,ratio,0,0);const count=Math.min(90,Math.max(35,Math.floor(innerWidth/18)));particles=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,r:Math.random()*1.5+.45,blue:Math.random()>.72}))}
function drawWallpaper(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;const md=Math.hypot(p.x-mouse.x,p.y-mouse.y);if(md<160){p.x+=(p.x-mouse.x)*.002;p.y+=(p.y-mouse.y)*.002}ctx.beginPath();ctx.fillStyle=p.blue?'rgba(76,154,255,.55)':'rgba(186,255,41,.48)';ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}for(let i=0;i<particles.length;i++)for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<125){ctx.beginPath();ctx.strokeStyle=`rgba(${a.blue?'76,154,255':'151,210,68'},${(1-d/125)*.14})`;ctx.lineWidth=.6;ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}if(motionOK)frame=requestAnimationFrame(drawWallpaper)}
addEventListener('resize',sizeWallpaper,{passive:true});addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY},{passive:true});document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(frame);if(!document.hidden&&motionOK)drawWallpaper()});sizeWallpaper();drawWallpaper();
