const jiraSection=document.querySelector('.agent-platform');if(jiraSection)jiraSection.id='jira';
const menu=document.querySelector('.menu'),header=document.querySelector('header');menu.addEventListener('click',()=>{const open=header.classList.toggle('open');menu.textContent=open?'Close':'Menu';menu.setAttribute('aria-expanded',open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,n=+el.dataset.count,start=performance.now();function run(now){let p=Math.min((now-start)/1100,1);el.textContent=Number.isInteger(n)?Math.round(n*p):(n*p).toFixed(1);if(p<1)requestAnimationFrame(run)}requestAnimationFrame(run);io.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>io.observe(el));
document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,email=f.querySelector('input').value;f.querySelector('p').textContent=`Thanks — we'll contact ${email} to schedule your walkthrough.`;f.reset()});

const resourceContent=[
  {label:'THREAT RESEARCH',title:'How attackers are operationalizing AI—and how defenders can get ahead',body:'Threat actors are using generative AI to accelerate reconnaissance, produce convincing social engineering, and adapt attacks faster. CyberSol helps defenders respond with unified telemetry, behavioral detection, automated investigation, and human-governed containment.',points:['Recognize AI-enabled attack patterns','Reduce investigation time with correlated evidence','Build safe, governed automation into incident response']},
  {label:'EXECUTIVE GUIDE',title:'The security leader’s blueprint for responsible AI adoption',body:'A practical framework for introducing autonomous capabilities into security operations without losing control. Start with high-volume, evidence-rich workflows, define approval boundaries, and measure quality alongside speed.',points:['Select the right first use cases','Define permissions and human approval points','Measure accuracy, time saved, and risk reduced']},
  {label:'CUSTOMER STORY',title:'How a global manufacturer transformed incident response',body:'A distributed manufacturer unified endpoint, identity, cloud, and network signals to eliminate manual handoffs. Automated enrichment gave analysts a complete incident timeline and enabled containment in 4.2 minutes.',points:['Unified fragmented security data','Automated triage and evidence collection','Reduced mean time to contain to 4.2 minutes']}
];
const modal=document.createElement('div');modal.className='resource-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="resource-dialog" role="dialog" aria-modal="true" aria-labelledby="resource-title"><button class="resource-close" aria-label="Close resource">×</button><p class="resource-label"></p><h2 id="resource-title"></h2><p class="resource-body"></p><ul></ul><a class="btn" href="#demo">Discuss this with our team →</a></div>';document.body.appendChild(modal);
const closeResource=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')};
document.querySelectorAll('.resources article').forEach((card,index)=>{card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label',`Open ${resourceContent[index].title}`);const open=()=>{const item=resourceContent[index],dialog=modal.querySelector('.resource-dialog');dialog.querySelector('.resource-label').textContent=item.label;dialog.querySelector('h2').textContent=item.title;dialog.querySelector('.resource-body').textContent=item.body;dialog.querySelector('ul').innerHTML=item.points.map(point=>`<li>${point}</li>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.resource-close').focus()};card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});
modal.querySelector('.resource-close').addEventListener('click',closeResource);modal.addEventListener('click',e=>{if(e.target===modal)closeResource()});modal.querySelector('a').addEventListener('click',closeResource);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeResource()});
