const menuButton=document.querySelector('.menu-button');
const nav=document.querySelector('#site-nav');
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const modal=document.querySelector('#demo-modal');
const content=document.querySelector('#modal-content');
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());
modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

const demos={
  onboarding:()=>`<div class="demo" data-step="1"><p class="eyebrow">Start Strong · Interactive sample</p><h2>Who can help?</h2><div class="demo-progress"><i style="width:33%"></i></div><p>It is your first morning. You cannot access the scheduling system, and your first team meeting begins in 20 minutes. What should you do first?</p><div class="choice-list"><button class="choice" data-correct="false">Wait until the meeting and mention it to everyone</button><button class="choice" data-correct="true">Contact IT support and let your supervisor know</button><button class="choice" data-correct="false">Ask a coworker to share their login</button></div><div class="feedback" hidden></div></div>`,
  safety:()=>`<div class="demo"><p class="eyebrow">Pause. Protect. Report. · Scenario</p><h2>Water and electricity</h2><div class="demo-progress"><i style="width:66%"></i></div><p>A resident reports water collecting near an electrical outlet in a hallway. The area is still open to foot traffic. What is the safest immediate response?</p><div class="choice-list"><button class="choice" data-correct="false">Touch the wall to determine whether it is wet</button><button class="choice" data-correct="false">Begin mopping before anyone sees the water</button><button class="choice" data-correct="true">Keep people away and follow the emergency escalation process</button></div><div class="feedback" hidden></div></div>`,
  phishing:()=>`<div class="demo"><p class="eyebrow">Spot the Signal · Inbox challenge</p><h2>Would you trust this message?</h2><div class="demo-progress"><i style="width:50%"></i></div><div class="email-demo"><dl><dt>From:</dt><dd>Vendor Services &lt;billing@vend0r-payments.example&gt;</dd><dt>Subject:</dt><dd>URGENT: Payment method changed</dd></dl><p>Hello, please use our <span class="clue">new payment account immediately</span>. Open the attachment to avoid a late fee. This change is confidential.</p></div><p>Select the best response.</p><div class="choice-list"><button class="choice" data-correct="false">Open the attachment to confirm the account number</button><button class="choice" data-correct="true">Verify through a known contact method and report the message</button><button class="choice" data-correct="false">Forward it to a coworker and ask them to test it</button></div><div class="feedback" hidden></div></div>`
};

function bindChoices(){document.querySelectorAll('.choice').forEach(button=>button.addEventListener('click',()=>{const box=content.querySelector('.feedback');const correct=button.dataset.correct==='true';document.querySelectorAll('.choice').forEach(b=>b.disabled=true);button.style.borderColor=correct?'var(--teal)':'var(--coral)';box.hidden=false;box.className='feedback'+(correct?'':' error');box.innerHTML=correct?'<strong>Good decision.</strong> This protects people or information while using the approved support process. Feedback explains why the action works—not only whether it is correct.':'<strong>Try a safer approach.</strong> Avoid actions that create additional risk. Use the approved support or escalation process and keep the right person informed.'}))}
document.querySelectorAll('.demo-button').forEach(button=>button.addEventListener('click',()=>{content.innerHTML=demos[button.dataset.demo]();modal.showModal();bindChoices()}));

const resources={
  facilitator:`<div class="resource-sheet"><p class="eyebrow">Sample supporting material</p><h2>New Employee Welcome<br>Facilitator Guide</h2><p><strong>Purpose:</strong> Help new employees connect their role to the organization and locate essential support.</p><table><tr><th>Time</th><th>Facilitator action</th><th>Learner activity</th></tr><tr><td>0–5 min</td><td>Welcome participants and display objectives.</td><td>Share one question about the first week.</td></tr><tr><td>5–15 min</td><td>Introduce the “Who can help?” map.</td><td>Match common needs to support teams.</td></tr><tr><td>15–25 min</td><td>Present the access-problem scenario.</td><td>Choose, discuss, and justify a response.</td></tr><tr><td>25–30 min</td><td>Summarize and answer questions.</td><td>Complete a personal first-week plan.</td></tr></table><p><strong>Accessibility note:</strong> Read scenario text aloud only as an optional reinforcement; all essential information appears in writing. Describe visuals and allow individual reflection before group discussion.</p><button class="button primary print-button" onclick="window.print()">Print / Save as PDF</button></div>`,
  checklist:`<div class="resource-sheet"><p class="eyebrow">Performance support · Job aid</p><h2>Pause. Protect. Report.</h2><p>Use this quick checklist when an incident could affect a resident, employee, or property.</p><table><tr><th>Step</th><th>Action</th></tr><tr><td><strong>1 · Pause</strong></td><td>Do not enter, touch, move, or investigate if doing so could create risk.</td></tr><tr><td><strong>2 · Protect</strong></td><td>Keep people at a safe distance. Follow site procedures for securing the area.</td></tr><tr><td><strong>3 · Report</strong></td><td>Use the approved emergency or supervisor escalation channel.</td></tr><tr><td><strong>4 · Record</strong></td><td>Document observable facts: location, time, people affected, and actions taken.</td></tr></table><p><em>This concept resource must be adapted to an employer’s approved safety policies and emergency contacts before use.</em></p><button class="button primary print-button" onclick="window.print()">Print / Save as PDF</button></div>`,
  evaluation:`<div class="resource-sheet"><p class="eyebrow">Measurement strategy</p><h2>Onboarding Evaluation Plan</h2><p>A practical measurement plan connects learner experience to workplace behavior without claiming invented outcomes.</p><table><tr><th>Level</th><th>Question</th><th>Evidence</th><th>Timing</th></tr><tr><td>Reaction</td><td>Was the experience relevant and usable?</td><td>3-item pulse survey</td><td>Immediately</td></tr><tr><td>Learning</td><td>Can employees make correct decisions?</td><td>Scenario assessment</td><td>End of week 1</td></tr><tr><td>Behavior</td><td>Are processes followed on the job?</td><td>Supervisor observation checklist</td><td>Day 30</td></tr><tr><td>Results</td><td>Did avoidable support needs change?</td><td>Trend in categorized help requests</td><td>Day 60–90</td></tr></table><button class="button primary print-button" onclick="window.print()">Print / Save as PDF</button></div>`
};
document.querySelectorAll('.resource').forEach(button=>button.addEventListener('click',()=>{content.innerHTML=resources[button.dataset.resource];modal.showModal()}));
